# Generated by Django 4.2.1 on 2023-05-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patientInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectid', models.IntegerField(max_length=4)),
                ('age', models.IntegerField(max_length=3)),
                ('height', models.FloatField(max_length=3)),
                ('weight', models.FloatField(max_length=3)),
                ('bmi', models.FloatField(max_length=2)),
            ],
        ),
    ]
