# Generated by Django 4.2.1 on 2023-05-30 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_patientinformation_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationInformation',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='healthcare.patientinformation')),
                ('casestart', models.IntegerField(default=0)),
                ('caseend', models.IntegerField()),
                ('anestart', models.IntegerField()),
                ('aneend', models.IntegerField()),
                ('opstart', models.IntegerField()),
                ('opend', models.IntegerField()),
                ('emop', models.CharField(max_length=1)),
                ('department', models.CharField(max_length=20)),
                ('optype', models.CharField(max_length=15)),
                ('dx', models.CharField(max_length=50)),
                ('opname', models.CharField(max_length=20)),
                ('approach', models.CharField(max_length=12)),
                ('position', models.CharField(max_length=25)),
                ('ane_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PreopInformation',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='healthcare.patientinformation')),
                ('preop_htn', models.CharField(max_length=1)),
                ('preop_dm', models.CharField(max_length=1)),
                ('preop_ecg', models.CharField(max_length=100)),
                ('preop_pft', models.CharField(max_length=30)),
                ('preop_hb', models.FloatField(max_length=4)),
                ('preop_plt', models.FloatField(max_length=6)),
                ('preop_pt', models.FloatField(max_length=5)),
                ('preop_aptt', models.FloatField(max_length=5)),
                ('preop_na', models.FloatField(max_length=5)),
                ('preop_k', models.FloatField(max_length=4)),
                ('preop_gluc', models.FloatField(max_length=5)),
                ('preop_alb', models.FloatField(max_length=4)),
                ('preop_ast', models.FloatField(max_length=6)),
                ('preop_alt', models.FloatField(max_length=6)),
                ('preop_bun', models.FloatField(max_length=5)),
                ('preop_cr', models.FloatField(max_length=5)),
                ('preop_ph', models.FloatField(max_length=6)),
                ('preop_hco3', models.FloatField(max_length=4)),
                ('preop_be', models.FloatField(max_length=4)),
                ('preop_pao2', models.FloatField(max_length=5)),
                ('preop_paco2', models.FloatField(max_length=4)),
                ('preop_sao2', models.FloatField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='sex',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='subjectid',
            field=models.IntegerField(),
        ),
    ]
