# Generated by Django 4.2.1 on 2023-05-30 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_operationinformation_preopinformation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntraopInformation',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='healthcare.patientinformation')),
                ('intraop_ebl', models.FloatField(max_length=7)),
                ('intraop_uo', models.FloatField(max_length=6)),
                ('intraop_rbc', models.FloatField(max_length=3)),
                ('intraop_ffp', models.FloatField(max_length=2)),
                ('intraop_crystalloid', models.FloatField(max_length=7)),
                ('intraop_colloid', models.FloatField(max_length=4)),
                ('intraop_ppf', models.FloatField(max_length=3)),
                ('intraop_mdz', models.FloatField(max_length=3)),
                ('intraop_ftn', models.FloatField(max_length=3)),
                ('intraop_rocu', models.FloatField(max_length=3)),
                ('intraop_vecu', models.FloatField(max_length=2)),
                ('intraop_eph', models.FloatField(max_length=3)),
                ('intraop_phe', models.FloatField(max_length=4)),
                ('intraop_epi', models.FloatField(max_length=5)),
                ('intraop_ca', models.FloatField(max_length=5)),
            ],
        ),
    ]
