# Generated by Django 4.2.1 on 2023-05-30 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0004_intraopinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intraopinformation',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='healthcare.patientinformation', unique=True),
        ),
        migrations.AlterField(
            model_name='operationinformation',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='healthcare.patientinformation', unique=True),
        ),
        migrations.AlterField(
            model_name='preopinformation',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='healthcare.patientinformation', unique=True),
        ),
    ]
